openapi: 3.0.1
info:
  title: TODO Lister
  description: A plugin that lists arbitrary todos.
  version: 'v1'
servers:
  - url: http://localhost:5173
paths:
  /api/todos:
    get:
      operationId: getTodos
      summary: Get list of tasks.
      responses:
        "200":
          description: OK
          content: 
            application/json:
              schema: 
                $ref: '#components/schemas/getTodoResponse'
components:
  schemas:
    getTodosResponse:
      type: object
      properties:
        todos:
          type: array
          items:
            type: string
          description: The list of todos.